-- Table for Product Reviews
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL, -- References sneakers(id) or apparel(id) logic handled in app or separate tables
  product_type TEXT NOT NULL, -- 'sneakers' or 'apparel' to distinguish
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Table for Coupons/Promo Codes
CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  discount_type TEXT CHECK (discount_type IN ('percent', 'fixed')) NOT NULL,
  discount_value INTEGER NOT NULL,
  min_purchase INTEGER DEFAULT 0,
  expiry_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Insert some dummy coupons
INSERT INTO coupons (code, discount_type, discount_value, min_purchase, expiry_date)
VALUES 
('WELCOME10', 'percent', 10, 0, NOW() + INTERVAL '1 year'),
('SAVE50K', 'fixed', 50000, 200000, NOW() + INTERVAL '1 month')
ON CONFLICT (code) DO NOTHING;
